yandex:
  folderId: ${YANDEX_FOLDER_ID}
  token: ${YANDEX_TOKEN}
  api-path: "https://translate.api.cloud.yandex.net/translate/v2/translate"

spring:
  datasource:
    url: jdbc:h2:mem:tinkoff-test
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver